---
- name: Install IIS
  win_feature: "name={{ item }} state=present restart=no include_sub_features=no include_management_tools=yes"
  with_items:
    - Web-Server
    - Web-Common-Http
    - Web-Default-Doc
    - Web-Dir-Browsing
    - Web-Http-Errors
    - Web-Static-Content
    - Web-Http-Redirect
    - Web-Health
    - Web-Http-Logging
    - Web-Request-Monitor
    - Web-Performance
    - Web-Stat-Compression
    - Web-Dyn-Compression
    - Web-Security
    - Web-Filtering
    - Web-Basic-Auth
    - Web-Windows-Auth
    - Web-App-Dev
    - Web-Net-Ext
    - Web-Net-Ext45
    - Web-Asp-Net
    - Web-Asp-Net45
    - Web-ISAPI-Ext
    - Web-ISAPI-Filter
